pygments:       false
permalink:      /:categories/:title/
paginate:       5

exclude:
    - README.md
    - Rakefile

title:          ScattPy
url:            http://scattpy.github.com
feed:           /atom.xml
description:    "scattpy - Python scikits package for light scattering computations."
comment:        Light Scattering methods for Python

author:
    name:       Alexander Vinokurov
    email:      alexaner.a.vinokurov@gmail.com
    
about: >
    
disqus:
    id:         vinokurov

nav:
    - name:     Blog
      url:      /
    
    - name:     Portfolio
      url:      /portfolio/
    
    - name:     About
      url:      /about/
      subnav:
        - name: Contact
          url:  mailto:scattpy-at-dotcom-after-googlegroups
    

footer:
      
copyright:
    - Design by <a href="http://ipsleung.com">Iris Leung</a>, Jekyll template by <a href="http://appden.com">Scott Kyle</a>
      
css:
    - /lib/appden.css
    - /lib/syntax.css
    
js:
    - http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js
    - /lib/mootools-more.js
    - /lib/appden.js
