pygments:       true
permalink:      /:categories/:title/
paginate:       10
paginate_file:  blog.html

exclude:
    - README.md
    - Rakefile

title:          ScattPy
url:            http://scattpy.github.com
feed:           /atom.xml
description:    "ScattPy - Python scikits package for light scattering computations."
comment:        Light Scattering methods for Python

author:
    name:       Alexander Vinokurov
    email:      alexaner.a.vinokurov@gmail.com
    
about: >
    
disqus:
    id:         scattpy

nav:
    - name:     Blog
      url:      /blog/
    
    - name:     Download
      url:      /download/

    - name:     Documentation
      url:      /docs/
      subnav:
              - name:   User Guide
                url:    /docs/user/
    
              - name:   Getting Started
                url:    /docs/user/getting_started.html
    
              - name:   Installation
                url:    /docs/user/installation.html

              - name:    ScattPy Reference
                url:     /docs/reference/
    
    - name:     About
      url:      /about/

    - name:     Contacts
      url:      /contacts/

footer:
      
copyright:
    - Design by <a href="http://ipsleung.com">Iris Leung</a>, Jekyll template by <a href="http://appden.com">Scott Kyle</a>
      
css:
    - /lib/syntax.css
    - /css/github.css
    - /css/tex.css
    - /css/main.css
    - /css/sphinx.css
    
js:
    - /lib/mootools.js
    - /lib/hub.js
    - /lib/googlelatex.js
    - /lib/bibcite.js

authors:
    scattpy:
        name:     ScattPy team
        full:     ScattPy team
        url:      http://scattpy.github.com
        email:    scattpy@googlegroups.com
    vinokurov:
        name:     Alexander Vinokurov
        full:     "Dr.&nbsp;A.A.&nbsp;Vinokurov"
        url:      http://alexander-vinokurov.com
        email:    alexander.a.vinokurov@gmail.com
        gravatar: 8d281fcf88c73c2c4503c7d12bc89e2a
    farafonov:
        name:     Victor Farafonov
        full:     "Prof.&nbsp;V.G.&nbsp;Farafonov"
        email:    far@aanet.ru
    ilin:
        name:     "Vladimir Il'in"
        full:     "Prof.&nbsp;V.B.&nbsp;Il'in"
        email:    vladimir_ilin@yahoo.com

bottom_nav:
      - title:   Get Help
        subitems:
               - title:  Getting Started
                 url:    /docs/user/getting_started.html
               - title:  Download
                 url:    /docs/user/download.html
               - title:  Installation
                 url:    /docs/user/installation.html
               - title:  Support
                 url:    mailto:scattpy@googlegroups.com
      - title:   Links
        subitems:
               - title:  Alexander Vinokurov
                 url:    http://alexander-vinokurov.com
               - title:  GitHub Repository
                 url:    http://github.com/ScattPy
               - title:  Google Groups
                 url:    http://groups.google.com/group/scattpy
               - title:  Bug Tracking
                 url:    http://github.com/ScattPy/scikits.scattpy/issues
